Fixes #11 - Move test sites to this repo
USGS-WiM/SS-IntegrationTester pull request #17
Opened 2022-05-06 04:56 UTC by amedenblik

Closes #11

2022-05-09 13:54 UTC, harper-wavra commented
I think this should also be into dev.

2022-05-09 13:56 UTC, amedenblik commented
Updated base branch!

2022-05-09 18:02 UTC, harper-wavra requested changes
Looks good, I think just update the change log and it should be good.

2022-05-09 18:02 UTC, harper-wavra commented on CHANGELOG.md
should add "added test sites"

2022-05-10 13:00 UTC, harper-wavra approved these changes

2022-05-10 13:00 UTC, merged